---
- name: Gather instance facts
  ansible.builtin.setup:

- name: Create group
  when:
    - etcd_group != "root"
  ansible.builtin.group:
    name: "{{ etcd_group }}"
    state: present
    system: "{{ etcd_group_system | bool }}"
    gid: "{{ etcd_group_gid | default(omit) }}"
  tags:
    - etcd

- name: Create user
  when:
    - etcd_user != "root"
  ansible.builtin.user:
    name: "{{ etcd_user }}"
    state: present
    shell: "{{ etcd_user_shell }}"
    system: "{{ etcd_user_system | bool }}"
    create_home: "{{ etcd_user_home is defined and etcd_user_system != true | bool }}"
    home: "{{ etcd_user_home | default(omit) }}"
    uid: "{{ etcd_user_uid | default(omit) }}"
    group: "{{ etcd_group }}"
  tags:
    - etcd

- name: Create etcd config directory
  ansible.builtin.file:
    state: directory
    path: "{{ etcd_conf_dir }}"
    mode: "{{ etcd_conf_dir_mode }}"
    owner: "{{ etcd_conf_dir_user }}"
    group: "{{ etcd_conf_dir_group }}"
  tags:
    - etcd

- name: Create etcd download directory
  ansible.builtin.file:
    state: directory
    path: "{{ etcd_download_dir }}"
    mode: "{{ etcd_download_dir_mode }}"
    owner: "{{ etcd_download_dir_user }}"
    group: "{{ etcd_download_dir_group }}"
  tags:
    - etcd

- name: Create etcd bin directory
  when:
    - etcd_bin_dir == "/usr/local/bin"
    - etcd_bin_dir == "/usr/local/bin/"
  ansible.builtin.file:
    state: directory
    path: "{{ etcd_bin_dir }}"
    mode: "{{ etcd_bin_dir_mode }}"
    owner: "{{ etcd_bin_dir_user }}"
    group: "{{ etcd_bin_dir_group }}"
  tags:
    - etcd

- name: Create etcd data directory
  ansible.builtin.file:
    state: directory
    path: "{{ etcd_data_dir }}"
    mode: "{{ etcd_data_dir_mode }}"
    owner: "{{ etcd_data_dir_user }}"
    group: "{{ etcd_data_dir_group }}"
  tags:
    - etcd

- name: Ensure correct owner/group for etcd data directory
  ansible.builtin.file:
    state: directory
    path: "{{ etcd_data_dir }}"
    owner: "{{ etcd_data_dir_user }}"
    group: "{{ etcd_data_dir_group }}"
    recurse: true
  tags:
    - etcd

- name: Copy certificates
  ansible.builtin.copy:
    src: "{{ etcd_ca_conf_directory }}/{{ item }}"
    dest: "{{ etcd_conf_dir }}/{{ item }}"
    mode: "0640"
    owner: "{{ etcd_conf_dir_user }}"
    group: "{{ etcd_conf_dir_group }}"
  with_items:
    - "{{ etcd_certificates }}"
  no_log: '{{ ansible_verbosity < 3 }}'
  tags:
    - etcd

- name: Downloading official etcd release
  ansible.builtin.get_url:
    url: "{{ etcd_download_url }}"
    dest: "{{ etcd_download_dir }}/etcd-v{{ etcd_version }}-linux-{{ etcd_architecture }}.tar.gz"
    checksum: "{{ etcd_download_url_checksum }}"
    mode: "0755"
  tags:
    - etcd
    - skip_ansible_lint

- name: Unzip downloaded file
  ansible.builtin.unarchive:
    src: "{{ etcd_download_dir }}/etcd-v{{ etcd_version }}-linux-{{ etcd_architecture }}.tar.gz"
    dest: "{{ etcd_download_dir }}/"
    remote_src: true
    owner: "root"
    group: "root"
    creates: "{{ etcd_download_dir }}/etcd-v{{ etcd_version }}-linux-{{ etcd_architecture }}/etcd"
  tags:
    - etcd

- name: Copy etcd binaries to destination directory
  ansible.builtin.copy:
    src: "{{ etcd_download_dir }}/etcd-v{{ etcd_version }}-linux-{{ etcd_architecture }}/{{ item }}"
    dest: "{{ etcd_bin_dir }}/{{ item }}"
    mode: "0755"
    owner: "root"
    group: "root"
    remote_src: true
  with_items:
    - etcd
    - etcdctl
  tags:
    - etcd

- name: Combine etcd_settings and etcd_settings_user (if defined)
  ansible.builtin.set_fact:
    etcd_settings: "{{ etcd_settings | combine(etcd_settings_user | default({})) }}"
  tags:
    - etcd
    - etcd-systemd

- name: Create systemd unit file
  ansible.builtin.template:
    src: etc/systemd/system/etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Reload systemd
  tags:
    - etcd
    - etcd-systemd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Enable and start etcd
  ansible.builtin.service:
    name: etcd
    enabled: true
    state: started
  tags:
    - etcd
