---
# Copyright (C) 2022 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Install etcd cluster
  hosts: k8s_etcd
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include etcd role
      ansible.builtin.include_role:
        name: githubixx.etcd
