---
# Copyright (C) 2022 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Setup cfssl
  hosts: etcd_assets
  become: true
  gather_facts: false
  tasks:
    - name: Include cfssl role
      ansible.builtin.include_role:
        name: githubixx.cfssl

- name: Update cache
  hosts: k8s_etcd
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

- name: Setup TLS certificates for etcd
  hosts: etcd_assets
  become: true
  gather_facts: false
  tasks:
    - name: Include kubernetes_ca role to generate TLS certificate files for etcd
      ansible.builtin.include_role:
        name: githubixx.kubernetes_ca

    - name: Copy certificate files from assets to local host
      ansible.posix.synchronize:
        mode: pull
        src: "{{ etcd_ca_conf_directory }}"
        dest: "/tmp"
